# This is the standard conda configuration file. Use this file to list
# the conda packages that you need installed in your environment.
channels:
  - conda-forge

dependencies:
  - nbgitpuller
  - pip
  - pip:
      - otter-grader==6.1.3
      - datascience
      # Allow users to download their home directories
      - jupyter-tree-download
